# Spring Datasource configuration
spring:
  datasource:
    # URL of the datasource.
    url: jdbc:hsqldb:mem:.
    # Username for the datasource.
    username: sa
    # Password for the datasource (empty in this case).
    password:
    # Driver class name for the datasource.
    driverClassName: org.hsqldb.jdbc.JDBCDriver
  jpa:
    # Disables the Open Session in View pattern.
    open-in-view: false
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 967313434685-bcfqtgn6tv5o2t8hlnjbqj7q195pv5i8.apps.googleusercontent.com
            client-secret: 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