name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:

      # Prepare
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
        
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@e6e38bacfdf1a337459f332974bb2327a31aaf4b

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Install Docker
        run: |
          curl -fsSL https://get.docker.com -o get-docker.sh
          sudo sh get-docker.sh
          sudo usermod -aG docker $USER
        
      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose --version
        
      - name: Set up Kafka Docker Compose 
        run: docker-compose -f docker-compose.yml up -d
      
      # Build
      - name: Sanitize kafka I
        run: ./gradlew build --no-daemon || true
        env:
          NINJA_PROFANITY_FILTER_API_KEY: ${{ secrets.NINJA_PROFANITY_FILTER_API_KEY }}
          GOOGLE_SAFE_BROWSING_API_KEY: ${{ secrets.GOOGLE_API_SAFETY_KEY }}
          KAFKA_BROKER_IP: localhost:9092
          SERVER_IP: localhost:8080

      - name: Sanitize kafka II
        run: ./gradlew build --no-daemon || true
        env:
          NINJA_PROFANITY_FILTER_API_KEY: ${{ secrets.NINJA_PROFANITY_FILTER_API_KEY }}
          GOOGLE_SAFE_BROWSING_API_KEY: ${{ secrets.GOOGLE_API_SAFETY_KEY }}
          KAFKA_BROKER_IP: localhost:9092
          SERVER_IP: localhost:8080

      - name: Build with Gradle
        run: ./gradlew build --no-daemon
        env:
          GOOGLE_SAFE_BROWSING_API_KEY: ${{ secrets.GOOGLE_API_SAFETY_KEY }}
          GOOGLE_CLIENT_ID_API_KEY: ${{ secrets.GOOGLE_CLIENT_ID_API_KEY }}
          GOOGLE_CLIENT_SECRET_API_KEY: ${{ secrets.GOOGLE_CLIENT_SECRET_API_KEY }}
          NINJA_PROFANITY_FILTER_API_KEY: ${{ secrets.NINJA_PROFANITY_FILTER_API_KEY }}
          KAFKA_BROKER_IP: localhost:9092
          SERVER_IP: localhost:8080
      
      # Test
      - name: Test with Gradle
        run: ./gradlew check --no-daemon
        env:
          GOOGLE_SAFE_BROWSING_API_KEY: ${{ secrets.GOOGLE_API_SAFETY_KEY }}
          GOOGLE_CLIENT_ID_API_KEY: ${{ secrets.GOOGLE_CLIENT_ID_API_KEY }}
          GOOGLE_CLIENT_SECRET_API_KEY: ${{ secrets.GOOGLE_CLIENT_SECRET_API_KEY }}
          NINJA_PROFANITY_FILTER_API_KEY: ${{ secrets.NINJA_PROFANITY_FILTER_API_KEY }}
          KAFKA_BROKER_IP: localhost:9092
          SERVER_IP: localhost:8080

      - name: Cleanup Gradle Cache GOOGLE_API_SAFETY_KEY
        run: |
          rm -f ~/.gradle/caches/modules-2/modules-2.lock
          rm -f ~/.gradle/caches/modules-2/gc.properties

      - name: Upload repository as artifact
        uses: actions/upload-artifact@v3
        with:
            name: repo-artifact
            path: .
            retention-days: 1
  
  deploy:
    runs-on: ubuntu-latest
    needs: build-test
    steps:

      - name: Download repository artifact
        uses: actions/download-artifact@v3
        with:
          name: repo-artifact
          path: .

      - name: Copy jar file
        run: |
          ls -lh .
          cp ./app/build/libs/app-0.2024.1-SNAPSHOT.jar .
          ls -lh .

      - name: Change permissions
        run: |
          chmod +x app-0.2024.1-SNAPSHOT.jar
          ls -lh app-0.2024.1-SNAPSHOT.jar
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          tags: app:latest
          push: false
          load: true
          build-args: |
            GOOGLE_CLIENT_ID_API_KEY=${{ secrets.GOOGLE_CLIENT_ID_API_KEY }}
            GOOGLE_SAFE_BROWSING_API_KEY=${{ secrets.GOOGLE_API_SAFETY_KEY }}
            GOOGLE_CLIENT_SECRET_API_KEY=${{ secrets.GOOGLE_CLIENT_SECRET_API_KEY }}
            NINJA_PROFANITY_FILTER_API_KEY=${{ secrets.NINJA_PROFANITY_FILTER_API_KEY }}
            KAFKA_BROKER_IP=kafka:9092
            SERVER_IP=${{secrets.AZURE_HOST}}

      - name: Check Docker Image
        run: docker images
      
      - name: Save Docker Image
        run: |
          docker save app:latest > app.tar
          ls -lh app.tar

      - name: Create SSH Key File
        run: |
          echo "${{ secrets.AZURE_SSH_KEY }}" > azure_ssh_key
          chmod 600 azure_ssh_key

      - name: copy docker-compose-deploy.yml via ssh key
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{secrets.AZURE_HOST}}
          username: ${{secrets.AZURE_USERNAME}}
          port: 22
          key: ${{ secrets.AZURE_SSH_KEY }}
          source: "docker-compose-deploy.yml"
          target: /home/${{secrets.AZURE_USERNAME}}
          overwrite: true

      - name: copy app.tar via ssh key
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{secrets.AZURE_HOST}}
          username: ${{secrets.AZURE_USERNAME}}
          port: 22
          key: ${{ secrets.AZURE_SSH_KEY }}
          source: "app.tar"
          target: /home/${{secrets.AZURE_USERNAME}}
          overwrite: true

      - name: executing remote ssh commands using ssh key
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{secrets.AZURE_HOST}}
          username: ${{secrets.AZURE_USERNAME}}
          port: 22
          key: ${{ secrets.AZURE_SSH_KEY }}
          script: |
            docker load < /home/${{secrets.AZURE_USERNAME}}/app.tar
            docker compose -f /home/${{secrets.AZURE_USERNAME}}/docker-compose-deploy.yml down
            docker compose -f /home/${{secrets.AZURE_USERNAME}}/docker-compose-deploy.yml up -d

      - name: Clean up SSH Key
        run: |
          rm -f azure_ssh_key


      




  
  
    