name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:

    # Prepare
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
        
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@e6e38bacfdf1a337459f332974bb2327a31aaf4b
      
      - name: Install Docker
        run: |
          curl -fsSL https://get.docker.com -o get-docker.sh
          sudo sh get-docker.sh
          sudo usermod -aG docker $USER
        
      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose --version

      #- name: Set up Docker Buildx
      #  uses: docker/setup-buildx-action@v3
        
      - name: Set up Kafka Docker Compose 
        run: docker-compose -f docker-compose.yml up -d
      
      # Build
      - name: Sanitize kafka I
        run: ./gradlew build --no-daemon || true
        env:
          NINJA_PROFANITY_FILTER_API_KEY: ${{ secrets.NINJA_PROFANITY_FILTER_API_KEY }}
          GOOGLE_SAFE_BROWSING_API_KEY: ${{ secrets.GOOGLE_API_SAFETY_KEY }}

      - name: Sanitize kafka II
        run: ./gradlew build --no-daemon || true
        env:
          NINJA_PROFANITY_FILTER_API_KEY: ${{ secrets.NINJA_PROFANITY_FILTER_API_KEY }}
          GOOGLE_SAFE_BROWSING_API_KEY: ${{ secrets.GOOGLE_API_SAFETY_KEY }}
          KAFKA_BROKER_IP: localhost:9092

      - name: Build with Gradle
        run: ./gradlew build --no-daemon
        env:
          GOOGLE_SAFE_BROWSING_API_KEY: ${{ secrets.GOOGLE_API_SAFETY_KEY }}
          GOOGLE_CLIENT_ID_API_KEY: ${{ secrets.GOOGLE_CLIENT_ID_API_KEY }}
          GOOGLE_CLIENT_SECRET_API_KEY: ${{ secrets.GOOGLE_CLIENT_SECRET_API_KEY }}
          NINJA_PROFANITY_FILTER_API_KEY: ${{ secrets.NINJA_PROFANITY_FILTER_API_KEY }}
          KAFKA_BROKER_IP: localhost:9092
      
      # Test
      - name: Test with Gradle
        run: ./gradlew check --no-daemon
        env:
          GOOGLE_SAFE_BROWSING_API_KEY: ${{ secrets.GOOGLE_API_SAFETY_KEY }}
          GOOGLE_CLIENT_ID_API_KEY: ${{ secrets.GOOGLE_CLIENT_ID_API_KEY }}
          GOOGLE_CLIENT_SECRET_API_KEY: ${{ secrets.GOOGLE_CLIENT_SECRET_API_KEY }}
          NINJA_PROFANITY_FILTER_API_KEY: ${{ secrets.NINJA_PROFANITY_FILTER_API_KEY }}
          KAFKA_BROKER_IP: localhost:9092

      - name: Cleanup Gradle Cache GOOGLE_API_SAFETY_KEY
        run: |
          rm -f ~/.gradle/caches/modules-2/modules-2.lock
          rm -f ~/.gradle/caches/modules-2/gc.properties

      - name: Upload repository as artifact
        uses: actions/upload-artifact@v3
        with:
            name: repo-artifact
            path: .
            retention-days: 1
  
  deploy:
    runs-on: ubuntu-latest
    needs: build-test
    steps:

      - name: Download repository artifact
        uses: actions/download-artifact@v3
        with:
          name: repo-artifact
          path: .

      - name: Copy jar file
        run: |
          ls -lh .
          cp ./app/build/libs/app-0.2024.1-SNAPSHOT.jar .
          ls -lh .

      - name: Change permissions
        run: |
          chmod +x app-0.2024.1-SNAPSHOT.jar
          ls -lh app-0.2024.1-SNAPSHOT.jar
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
            context: .
            tags: app:latest
            push: false
            build-args: |
              GOOGLE_CLIENT_ID_API_KEY=${{ secrets.GOOGLE_CLIENT_ID_API_KEY }}
              GOOGLE_SAFE_BROWSING_API_KEY=${{ secrets.GOOGLE_API_SAFETY_KEY }}
              GOOGLE_CLIENT_SECRET_API_KEY=${{ secrets.GOOGLE_CLIENT_SECRET_API_KEY }}
              NINJA_PROFANITY_FILTER_API_KEY=${{ secrets.NINJA_PROFANITY_FILTER_API_KEY }}
              KAFKA_BROKER_IP=kafka:9092
      
      - name: Check Docker Image
        run: docker images 
      
      - name: Export docker image
        run: |
          docker save app:latest > app.tar
          ls -lh app.tar

      - name: Upload docker
        uses: actions/upload-artifact@v3
        with:
          path: .
          name: app.tar

      #- name: Copy docker-compose-deploy.yml to Azure VM
      #  run: |
      #    cp repo-artifact/docker-compose-deploy.yml .
      #    ls -lh docker-compose-deploy.yml

      #- name: Copy app.jar to Azure VM
      #  run: |
      #    cp app.jar docker-compose-deploy/app.jar
      #    ls -lh docker-compose-deploy/app.jar

      #- name: Load docker image
      #  run: |
      #    docker load < /home/${{AZURE_USERNAME}}.app.tar
      #    docker images


      




  
  
    